# Generated by Django 4.0.4 on 2022-04-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted title',
            new_name='title',
        ),
    ]
